apiVersion: v1
kind: Pod
metadata:
  name: curl-pod
spec:
  containers:
    - name: curl-container
      image: curlimages/curl:latest  # Use the official curl image
      command:
        - /bin/sh
        - -c
        - |
          while true; do
            curl --location 'http://order.order/order/v1' \
            --header 'Content-Type: application/json' \
            --data '{}'
            sleep 1  # Adjust the sleep interval as needed
          done  # Keep the container running
