apiVersion: v1
kind: Namespace
metadata:
  name: order
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  namespace: order
  labels:
    app: order
    color: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      name: order
      labels:
        app: order
        color: blue
    spec:
      containers:
        - name: order
          image: marcusantunius/order:v1
          imagePullPolicy: Always
          envFrom:
          - configMapRef:
              name: order-blue

      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-alb
  namespace: order
  labels:
    app: order
    color: green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      name: order
      labels:
        app: order
        color: green
    spec:
      containers:
        - name: order
          image: marcusantunius/order:v1
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: order-green

      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: order
  namespace: order
spec:
  selector:
    app: order
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
    - protocol: TCP
      port: 443
      targetPort: 443
      name: https
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: order
  name: order-blue
data:
  restaurantv2: "http://restaurant.restaurant"
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: order
  name: order-green
data:
  restaurantv2: "http://k8s-restaura-restaura-13c720b2f0-881967216.us-east-1.elb.amazonaws.com/"