apiVersion: v1
kind: Namespace
metadata:
  name: order
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  namespace: order
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      name: order
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: marcusantunius/order:v1
          imagePullPolicy: IfNotPresent
          envFrom:
          - configMapRef:
              name: order

      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: order
  namespace: order
spec:
  selector:
    app: order
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
    - protocol: TCP
      port: 443
      targetPort: 443
      name: https
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: order
  name: order
data:
  restaurantv2: "http://restaurant.restaurant"